negocio_wb/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('nucleo.urls',namespace='nucleo') ),
    path('tienda/', include('tienda.urls',namespace='tienda') ),
]


from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

nucleo/urls.py
from django.urls import path
from . import views

app_name='nucleo'

urlpatterns = [
    path('',views.index,name='index'),
]

tienda/urls.py
from django.urls import path
from . import views

app_name='tienda'

urlpatterns = [
#    path('',views.tienda_inicio,name='tienda_inicio'),
path('',views.lista_productos,name='lista_productos'),
path('<slug:categoria_slug>/',views.lista_productos,name='lista_productos_por_categoria'),
path('<int:id>/<slug:slug>/',views.producto_detalle,name='producto_detalle'),
]

servicios/models.py
from django.db import models

# Create your models here.

tienda/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Categoria(models.Model):
    nombre = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, unique=True)

    class Meta:
        ordering = ('nombre',)
        verbose_name = 'Categoria'
        verbose_name_plural = 'Categorias'
    
    def __str__(self):
        return self.nombre
    
    def get_absolute_url(self):
        return reverse('tienda:lista_productos_por_categoria',
                        args=[self.slug])

class Producto(models.Model):
    categoria = models.ForeignKey(Categoria, related_name='productos',
                                on_delete=models.CASCADE)
    nombre = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    imagen = models.ImageField(upload_to='productos/%Y/%m/%d', blank=True)
    descripcion = models.TextField(blank=True)
    precio = models.DecimalField(max_digits=10, decimal_places=2)
    disponibilidad = models.BooleanField(default=True)
    creado = models.DateTimeField(auto_now_add=True)
    actualizado = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('nombre',)
        verbose_name = 'Producto'
        verbose_name_plural = 'Productos'
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.nombre
    
    def get_absolute_url(self):
        return reverse('tienda:producto_detalle', 
                        args=[self.id, self.slug])
    
    

nucleo/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.

def index (request):
    return render(request,template_name="nucleo/index.html")

servicios/views.py
from django.shortcuts import render

# Create your views here.

tienda/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import Categoria, Producto

# Create your views here.
def tienda_inicio(request):
    return HttpResponse("<h1> Bienvenido a la tienda </h1>")

def lista_productos(request, categoria_slug=None):
    categoria = None
    categorias = Categoria.objects.all()
    print('Las categorias son: ')
    print(categorias)
    productos = Producto.objects.filter(disponibilidad=True)
    print('Los productos son: ')
    print(productos)
    if categoria_slug:
        categoria = get_object_or_404(Categoria, slug=categoria_slug)
        productos = productos.filter(categoria=categoria)
    print('Llegamos aqui')
    return render(request, 'tienda/productos/lista.html',
                    {'categoria': categoria,
                    'categorias': categorias,
                    'productos': productos})

def producto_detalle(request, id, slug):
    producto = get_object_or_404(Producto, id=id, 
                                slug=slug, disponibilidad=True)
    return render(request, 'tienda/productos/detalles.html',
                            {'producto':producto})

mi_negocio_web/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Mi negocio online</title>
    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <!-- Fuentes -->
    <link href="{% static 'css/fontawesome-free/css/all.css' %}" rel="stylesheet">
    <link href="{% static 'css/simple-line-icons/css/simple-line-icons.css' %}" rel="stylesheet">
    <!-- Estilos personalizados -->
    <link href="{% static 'css/pagina_inicio.css' %}" rel="stylesheet">
    <link href="{% static 'css/base.css' %} " rel="stylesheet ">
    <link rel='shortcut icon' type='image/x-icon' href="{% static 'img/favicon.ico'%}" />
</head>

<body>
    <main>
        <!-- Barra de navegación -->
        <nav class=" navbar navbar-expand-sm bg-light ">
            <div class="container-fluid ">
                <a class="navbar-brand " href="# ">
                    <img src="https://upload.wikimedia.org/wikipedia/commons/c/c3/Python-logo-notext.svg" 
                    width="30 " height="30 " class="d-inline-block align-top " alt=" "> PNL-ACTUMLOGOS
                </a>
                <ul class="navbar-nav ">
                    <li class="nav-item ">
                        <a class="nav-link " href="# ">Nosotros</a>
                    </li>

                    <li class="nav-item ">
                        <a class="nav-link " href="# ">Productos</a>
                    </li>

                    <li class="nav-item ">
                        <a class="nav-link " href="# ">Servicios</a>
                    </li>
                    <li class="nav-item ">
                        <a class="nav-link " href="# ">Contacto</a>
                    </li>
                </ul>
                <form class="form">
                    <div class="cart">
                        {% with total_items=carrito|length%}
                            {% if total_items > 0%}
                            Tu carrito:
                            <a href="{% url "carrito:carrito_detalle"%}">
                                {{ total_items }}
                                producto{{ total_items|pluralize}},
                                ${{ carrito.obtener_precio_total }}
                            </a>
                            {% else %}
                                Tu carrito esta vacio
                            {% endif %}
                        {% endwith %}
                    </div>
                    <a class="btn btn-primary " href="{% url "account_login" %}">Iniciar Sesión</a>
                </form>
            </div>
        </nav>

        <!-- Contenido de la página-->
        <div id="content">
            {% block content %} 
            {% endblock%}
        </div>
        <!-- Footer -->
        <footer class="footer bg-light ">
            <div class="container-fluid ">
                <div class="row ">
                    <div class="col-lg-6 h-100 text-center text-lg-left my-auto ">
                        <ul class="list-inline mb-2 ">
                            <li class="list-inline-item ">
                                <a href="# ">Nosotros</a>
                            </li>
                            <li class="list-inline-item ">&sdot;</li>
                            <li class="list-inline-item ">
                                <a href="# ">Contacto</a>
                            </li>
                            <li class="list-inline-item ">&sdot;</li>
                            <li class="list-inline-item ">
                                <a href="# ">Términos de uso</a>
                            </li>
                            <li class="list-inline-item ">&sdot;</li>
                            <li class="list-inline-item ">
                                <a href="# ">Política de privacidad</a>
                            </li>
                        </ul>
                        <p class="text-muted small mb-4 mb-lg-0 ">&copy; 
                        PNL-Actumlogos 2021. Todos los derechos reservados.</p>
                    </div>
                    <div class="col-lg-6 h-100 text-center text-lg-right my-auto ">
                        <ul class="list-inline mb-0 ">
                            <li class="list-inline-item mr-3 ">
                                <a href="https://www.facebook.com ">
                                    <i class="fab fa-facebook fa-2x fa-fw "></i>
                                </a>
                            </li>
                            <li class="list-inline-item mr-3 ">
                                <a href="https://twitter.com/ ">
                                    <i class="fab fa-twitter-square fa-2x fa-fw "></i>
                                </a>
                            </li>
                            <li class="list-inline-item ">
                                <a href="https://www.instagram.com ">
                                    <i class="fab fa-instagram fa-2x fa-fw "></i>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </footer>
    </main>
</body>

</html>

negocio_wb/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Mi negocio online</title>
    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <!-- Fuentes -->
    <link href="{% static 'css/fontawesome-free/css/all.css' %}" rel="stylesheet">
    <link href="{% static 'css/simple-line-icons/css/simple-line-icons.css' %}" rel="stylesheet">
    <!-- Estilos personalizados -->
    <link href="{% static 'css/pagina_inicio.css' %}" rel="stylesheet">
    <link href="{% static 'css/base.css' %} " rel="stylesheet ">
    <link rel='shortcut icon' type='image/x-icon' href="{% static 'img/favicon.ico'%}" />
</head>

<body>
    <main>
        <!-- Barra de navegación -->
        <nav class=" navbar navbar-expand-sm bg-light ">
            <div class="container-fluid ">
                <a class="navbar-brand " href="# ">
                    <img src="https://upload.wikimedia.org/wikipedia/commons/c/c3/Python-logo-notext.svg" 
                    width="30 " height="30 " class="d-inline-block align-top " alt=" "> PNL-ACTUMLOGOS
                </a>
                <ul class="navbar-nav ">
                    <li class="nav-item ">
                        <a class="nav-link " href="# ">Nosotros</a>
                    </li>

                    <li class="nav-item ">
                        <a class="nav-link " href="# ">Productos</a>
                    </li>

                    <li class="nav-item ">
                        <a class="nav-link " href="# ">Servicios</a>
                    </li>
                    <li class="nav-item ">
                        <a class="nav-link " href="# ">Contacto</a>
                    </li>
                </ul>
                <form class="form">
                    <div class="cart">
                        Tu carrito esta vacio
                    </div>
                    <a class="btn btn-primary " href="# ">Iniciar Sesión</a>
                </form>
            </div>
        </nav>

        <!-- Contenido de la página-->
        <div id="content">
            {% block content %} 
            {% endblock%}
        </div>
        <!-- Footer -->
        <footer class="footer bg-light ">
            <div class="container-fluid ">
                <div class="row ">
                    <div class="col-lg-6 h-100 text-center text-lg-left my-auto ">
                        <ul class="list-inline mb-2 ">
                            <li class="list-inline-item ">
                                <a href="# ">Nosotros</a>
                            </li>
                            <li class="list-inline-item ">&sdot;</li>
                            <li class="list-inline-item ">
                                <a href="# ">Contacto</a>
                            </li>
                            <li class="list-inline-item ">&sdot;</li>
                            <li class="list-inline-item ">
                                <a href="# ">Términos de uso</a>
                            </li>
                            <li class="list-inline-item ">&sdot;</li>
                            <li class="list-inline-item ">
                                <a href="# ">Política de privacidad</a>
                            </li>
                        </ul>
                        <p class="text-muted small mb-4 mb-lg-0 ">&copy; 
                        PNL-Actumlogos 2021. Todos los derechos reservados.</p>
                    </div>
                    <div class="col-lg-6 h-100 text-center text-lg-right my-auto ">
                        <ul class="list-inline mb-0 ">
                            <li class="list-inline-item mr-3 ">
                                <a href="https://www.facebook.com ">
                                    <i class="fab fa-facebook fa-2x fa-fw "></i>
                                </a>
                            </li>
                            <li class="list-inline-item mr-3 ">
                                <a href="https://twitter.com/ ">
                                    <i class="fab fa-twitter-square fa-2x fa-fw "></i>
                                </a>
                            </li>
                            <li class="list-inline-item ">
                                <a href="https://www.instagram.com ">
                                    <i class="fab fa-instagram fa-2x fa-fw "></i>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </footer>
    </main>
</body>

</html>

nucleo/templates/nucleo/index.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Mi negocio online</title>
    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <!-- Fuentes -->
    <link href="{% static 'css/fontawesome-free/css/all.css' %}" rel="stylesheet">
    <link href="{% static 'css/simple-line-icons/css/simple-line-icons.css' %}" rel="stylesheet">
    <!-- Estilos personalizados -->
    <link href="{% static 'css/pagina_inicio.css' %}" rel="stylesheet">
    <link href="{% static 'css/base.css' %} " rel="stylesheet ">
    <link rel='shortcut icon' type='image/x-icon' href="{% static 'img/favicon.ico'%}" />
</head>

<body>
    <main>
        <!-- Barra de navegación -->
        <nav class=" navbar navbar-expand-sm bg-light ">
            <div class="container-fluid ">
                <a class="navbar-brand " href="# ">
                    <img src="https://upload.wikimedia.org/wikipedia/commons/c/c3/Python-logo-notext.svg " width="30 " height="30 " class="d-inline-block align-top " alt=" "> PNL-ACTUMLOGOS
                </a>
                <ul class="navbar-nav ">
                    <li class="nav-item ">
                        <a class="nav-link " href="# ">Nosotros</a>
                    </li>

                    <li class="nav-item ">
                        <a class="nav-link " href="# ">Productos</a>
                    </li>

                    <li class="nav-item ">
                        <a class="nav-link " href="# ">Servicios</a>
                    </li>
                    <li class="nav-item ">
                        <a class="nav-link " href="# ">Contacto</a>
                    </li>
                </ul>
                <form class="form ">
                    <a class="btn btn-primary " href="# ">Iniciar Sesión</a>
                </form>
            </div>
        </nav>

        <!-- Contenido de la página-->
        <div id="content ">
            <header class="masthead text-white text-center ">
                <div class="overlay "></div>
                <div class="container ">
                    <div class="row ">
                        <div class="col-xl-9 mx-auto ">
                            <h1 class="mb-5 ">Descubre productos y servicios relacionados con IA</h1>
                        </div>
                    </div>
                </div>
            </header>
            <!-- Iconos -->
            <section class="features-icons bg-light text-center ">
                <div class="container ">
                    <div class="row ">
                        <div class="col-lg-4 ">
                            <div class="features-icons-item mx-auto mb-5 mb-lg-0 mb-lg-3 ">
                                <div class="features-icons-icon d-flex ">
                                    <i class="icon-screen-desktop m-auto text-primary "></i>
                                </div>
                                <h3>Soluciones de Inteligencia Artificial</h3>
                                <p class="lead mb-0 ">Ofrecemos servicios relacionados con todas las áreas de la IA</p>
                            </div>
                        </div>
                        <div class="col-lg-4 ">
                            <div class="features-icons-item mx-auto mb-5 mb-lg-0 mb-lg-3 ">
                                <div class="features-icons-icon d-flex ">
                                    <i class="icon-layers m-auto text-primary "></i>
                                </div>
                                <h3>Soluciones en venta de tecnología</h3>
                                <p class="lead mb-0 ">Tenemos diversos productos relacionados con el desarrollo de sistemas inteligentes</p>
                            </div>
                        </div>
                        <div class="col-lg-4 ">
                            <div class="features-icons-item mx-auto mb-0 mb-lg-3 ">
                                <div class="features-icons-icon d-flex ">
                                    <i class="icon-check m-auto text-primary "></i>
                                </div>
                                <h3>Enterate de lo último en IA</h3>
                                <p class="lead mb-0 ">Unete a nuestro boletin informativo para enterarte de las últimas tendencias</p>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </div>
        <!-- Footer -->
        <footer class="footer bg-light ">
            <div class="container-fluid ">
                <div class="row ">
                    <div class="col-lg-6 h-100 text-center text-lg-left my-auto ">
                        <ul class="list-inline mb-2 ">
                            <li class="list-inline-item ">
                                <a href="# ">Nosotros</a>
                            </li>
                            <li class="list-inline-item ">&sdot;</li>
                            <li class="list-inline-item ">
                                <a href="# ">Contacto</a>
                            </li>
                            <li class="list-inline-item ">&sdot;</li>
                            <li class="list-inline-item ">
                                <a href="# ">Términos de uso</a>
                            </li>
                            <li class="list-inline-item ">&sdot;</li>
                            <li class="list-inline-item ">
                                <a href="# ">Política de privacidad</a>
                            </li>
                        </ul>
                        <p class="text-muted small mb-4 mb-lg-0 ">&copy; PNL-Actumlogos 2021. Todos los derechos reservados.</p>
                    </div>
                    <div class="col-lg-6 h-100 text-center text-lg-right my-auto ">
                        <ul class="list-inline mb-0 ">
                            <li class="list-inline-item mr-3 ">
                                <a href="https://www.facebook.com ">
                                    <i class="fab fa-facebook fa-2x fa-fw "></i>
                                </a>
                            </li>
                            <li class="list-inline-item mr-3 ">
                                <a href="https://twitter.com/ ">
                                    <i class="fab fa-twitter-square fa-2x fa-fw "></i>
                                </a>
                            </li>
                            <li class="list-inline-item ">
                                <a href="https://www.instagram.com ">
                                    <i class="fab fa-instagram fa-2x fa-fw "></i>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </footer>
    </main>
</body>

</html>

servicios/templates/servicios/mnist.html
{% extends "base.html" %} 
{% load static %} 
{% block content %}
<div class="container-fluid">
    <div class="row">
        <div style="height: 550px;" class="col-sm-3">
            <h3>Servicios</h3>
            <ul>
                <li> 
                    <a href='#'>Reconocimiento de digitos</a> 
                </li>
                <li> 
                    <a href='#'>Conversión de archivos</a> 
                </li>
                <li> 
                    <a href='#'>Transferencia de estilo</a> 
                </li>
            </ul>
        </div>
        <div class="col-sm-9">
                <h3>Clasificación de digitos en imagenes</h3>
                {% if url is not None%}
                <img src="{{url}}" width="400px" height="400px" 
                alt="prediccion">
                <h4>En la imagen hay un número: {{predictedLabel}}</h4>
                {% else %}
                <img src="{%static "/ml/mnist.jpg"%}" width="400px" 
                height="400px" 
                alt="digitos">
                <br><br> 
                {% endif %}
                <form method="post" enctype="multipart/form-data" 
                action="mnist-inicio">
                    {% csrf_token %}
                    <input name="files" type="file" required><br><br>
                    <button class="btn btn-primary" type="submit">
                    Predicción</button>
                </form>
        </div>
    </div>
</div>
{% endblock %}

tienda/templates/tienda/productos/detalles.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <div class="product-detail">
        <img src="{% if producto.imagen %}{{ producto.imagen.url }}{% else %}
        {% static "img/no_image.png" %}{% endif %}">
        <h3>{{ producto.nombre }}</h3>
        <h4>
            <a href="{{ producto.categoria.get_absolute_url }}">
                {{ producto.categoria }}
            </a>
        </h4>
        <p class="precio">${{ producto.precio }}</p>
        {{ producto.descripcion|linebreaks }}
    </div>
{% endblock %}

tienda/templates/tienda/productos/lista.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="container-fluid">
<div class="row">
<div style="height: 550px;" class="col-sm-3"> 
        <h3>Categorías</h3>
        <ul>
            <li {% if not categoria %}class="selected"{% endif %}>
                <a href="{% url "tienda:lista_productos" %}">Todos</a>
            </li>
            {% for c in categorias %}
                <li {% if categoria.slug == c.slug %}class="selected"
                {% endif %}>
                    <a href="{{ c.get_absolute_url }}">{{ c.nombre }}</a>
                </li>
            {% endfor %}
        </ul>
</div>
<div class="col-sm-9"> 
    <div id="main" class="product-list">
            <h3>{% if categoria %}{{ categoria.nombre }}{% else %}Productos 
            {% endif %}</h3>
            {% for producto in productos %}
                <div class="item">
                    <a href="{{ producto.get_absolute_url }}">
                        <img src="{% if producto.imagen %}{{ producto.imagen.url }}
                        {%else %}{% static "img/no_image.png" %}{% endif %}">
                    </a>
                    <a href="{{ producto.get_absolute_url }}">{{ producto.nombre }}</a>
                    <br>
                    ${{ producto.precio }}
                </div>
            {% endfor %}
    </div>
</div>
</div>
</div>
{% endblock %}